# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VersusBattle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'SDWebImage'
 pod 'ReachabilitySwift'
 pod 'Adjust'
 pod 'OneSignal/OneSignal', '>= 5.2.9', '< 6.0'

end
